openapi: 3.0.0
info:
  x-skaffolder-id-project: 5ee3c509a360c675ce53e620
  title: bookstore
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  "/user/{id}/changePassword":
    post:
      x-skaffolder-id: 5ee3c50aa360c675ce53e62f
      x-skaffolder-name: changePassword
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: Change password of user from admin
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: object
      x-skaffolder-url: /{id}/changePassword
      x-skaffolder-roles:
        - 5ee3c50aa360c675ce53e62c
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK
  /user:
    post:
      x-skaffolder-id: 5ee3c50aa360c675ce53e62d
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id: 5ee3c50aa360c675ce53e62e
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/user/{id}":
    delete:
      x-skaffolder-id: 5ee3c50aa360c675ce53e634
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5ee3c50aa360c675ce53e631
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id: 5ee3c50aa360c675ce53e630
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5ee3c50aa360c675ce53e62a
      x-skaffolder-resource: User
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Author:
      x-skaffolder-id: 5ee3d859a360c675ce53e6ee
      x-skaffolder-id-db: 5ee3c509a360c675ce53e621
      x-skaffolder-id-entity: 5ee3d859a360c675ce53e6e9
      x-skaffolder-url: /author
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        books:
          type: string
          x-skaffolder-id-attr: 5ee3d859a360c675ce53e6ed
          x-skaffolder-type: String
        dateOfBirth:
          type: integer
          x-skaffolder-id-attr: 5ee3d859a360c675ce53e6eb
          x-skaffolder-type: Date
        dateOfDeath:
          type: integer
          x-skaffolder-id-attr: 5ee3d859a360c675ce53e6ec
          x-skaffolder-type: Date
        name:
          type: string
          x-skaffolder-id-attr: 5ee3d859a360c675ce53e6ea
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
    Book:
      x-skaffolder-id: 5ee3d632a360c675ce53e6cf
      x-skaffolder-id-db: 5ee3c509a360c675ce53e621
      x-skaffolder-id-entity: 5ee3d632a360c675ce53e6ca
      x-skaffolder-url: /book
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        ISBN:
          type: string
          x-skaffolder-id-attr: 5ee3d632a360c675ce53e6cd
          x-skaffolder-type: String
          x-skaffolder-required: true
          x-skaffolder-unique: true
        author:
          type: string
          x-skaffolder-id-attr: 5ee3d632a360c675ce53e6cc
          x-skaffolder-type: String
        category:
          type: string
          x-skaffolder-id-attr: 5ee3d632a360c675ce53e6ce
          x-skaffolder-type: String
        genre:
          type: string
          x-skaffolder-id-attr: 5ee3d795a360c675ce53e6df
          x-skaffolder-type: String
        language:
          type: string
          x-skaffolder-id-attr: 5ee3d795a360c675ce53e6e0
          x-skaffolder-type: String
        sumary:
          type: string
          x-skaffolder-id-attr: 5ee3d795a360c675ce53e6e1
          x-skaffolder-type: String
        title:
          type: string
          x-skaffolder-id-attr: 5ee3d632a360c675ce53e6cb
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
        - ISBN
    Cart:
      x-skaffolder-id: 5ee3d6d3a360c675ce53e6dd
      x-skaffolder-id-db: 5ee3c509a360c675ce53e621
      x-skaffolder-id-entity: 5ee3d6d3a360c675ce53e6db
      x-skaffolder-url: /cart
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        Books:
          type: string
          x-skaffolder-id-attr: 5ee3d6d3a360c675ce53e6dc
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
    Genre:
      x-skaffolder-id: 5ee3d7e2a360c675ce53e6e6
      x-skaffolder-id-db: 5ee3c509a360c675ce53e621
      x-skaffolder-id-entity: 5ee3d7e2a360c675ce53e6e4
      x-skaffolder-url: /genre
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        name:
          type: string
          x-skaffolder-id-attr: 5ee3d7e2a360c675ce53e6e5
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
    User:
      x-skaffolder-id: 5ee3c50aa360c675ce53e62a
      x-skaffolder-id-db: 5ee3c509a360c675ce53e621
      x-skaffolder-id-entity: 5ee3c509a360c675ce53e622
      x-skaffolder-url: /user
      x-skaffolder-type: User
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        mail:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e625
          x-skaffolder-type: String
        name:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e626
          x-skaffolder-type: String
        password:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e624
          x-skaffolder-type: String
          x-skaffolder-required: true
        roles:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e628
          x-skaffolder-type: String
        surname:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e627
          x-skaffolder-type: String
        username:
          type: string
          x-skaffolder-id-attr: 5ee3c509a360c675ce53e623
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - password
        - username
  x-skaffolder-db:
    - x-skaffolder-id: 5ee3c509a360c675ce53e621
      x-skaffolder-name: bookstore_db
  x-skaffolder-page:
    - x-skaffolder-id: 5ee3c509a360c675ce53e629
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 5ee3c50aa360c675ce53e62c
      x-skaffolder-name: ADMIN
