/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE authorBaseService PLEASE EDIT ../author.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Author } from '../../domain/bookstore_db/author';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Author.service.ts
 */

/*
 * SCHEMA DB Author
 *
	{
		books: {
			type: 'String'
		},
		dateOfBirth: {
			type: 'Date'
		},
		dateOfDeath: {
			type: 'Date'
		},
		name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		authors: [{
			type: Schema.ObjectId,
			ref : "Book"
		}],
	}
 *
 */
@Injectable()
export class AuthorBaseService {

    contextUrl: string = environment.endpoint + '/author';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * AuthorService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Author): Observable<Author> {
        return this.http
            .post<Author>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * AuthorService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AuthorService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Author> {
        return this.http
            .get<Author>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AuthorService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Author[]> {
        return this.http
            .get<Author[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * AuthorService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Author): Observable<Author> {
        return this.http
            .post<Author>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
